package com.priorities.reservation;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.UUID;

public class ReservationApp extends JFrame {
    private static final long serialVersionUID = 1L;
    private CardLayout cards = new CardLayout(); private JPanel pages = new JPanel(cards);
    private Color navy = new Color(25, 57, 84), orange = new Color(232, 125, 45);
    public ReservationApp() { super("RailWay Reservation System"); add(pages); pages.add(loginPage(), "login"); pages.add(bookPage(), "book"); pages.add(cancelPage(), "cancel"); cards.show(pages,"login"); setSize(760,580);setLocationRelativeTo(null);setDefaultCloseOperation(EXIT_ON_CLOSE); }
    private JPanel base(String title) { JPanel p=new JPanel(new BorderLayout());p.setBorder(BorderFactory.createEmptyBorder(22,55,22,55)); JLabel h=new JLabel(title);h.setFont(new Font("SansSerif",Font.BOLD,26));h.setForeground(navy);p.add(h,BorderLayout.NORTH);return p; }
    private JButton button(String text) { JButton b=new JButton(text);b.setBackground(orange);b.setForeground(Color.WHITE);b.setFocusPainted(false);return b; }
    private JPanel loginPage() { JPanel p=base("Welcome to RailWay"); JPanel form=new JPanel(new GridLayout(5,1,8,8)); JTextField user=new JTextField(); JPasswordField pass=new JPasswordField(); form.add(new JLabel("Username"));form.add(user);form.add(new JLabel("Password"));form.add(pass);JButton go=button("Sign in");form.add(go);go.addActionListener(e->{try{if(Database.authenticate(user.getText().trim(),new String(pass.getPassword()))){cards.show(pages,"book");}else JOptionPane.showMessageDialog(this,"Access denied. Check your username and password.","Login",JOptionPane.ERROR_MESSAGE);}catch(SQLException x){problem(x);}});p.add(form,BorderLayout.CENTER);p.add(new JLabel("Demo account: admin / admin123",SwingConstants.CENTER),BorderLayout.SOUTH);return p; }
    private JPanel bookPage() { JPanel p=base("Book a Ticket"); JPanel f=new JPanel(new GridLayout(0,2,10,10)); JTextField name=new JTextField(), no=new JTextField(), train=new JTextField(), date=new JTextField(), source=new JTextField(), destination=new JTextField(); train.setEditable(false); JComboBox<String> cls=new JComboBox<String>(new String[]{"First AC","Second AC","Third AC","Sleeper","Chair Car"});
        no.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){set();}public void removeUpdate(DocumentEvent e){set();}public void changedUpdate(DocumentEvent e){set();}private void set(){train.setText(Database.TRAINS.getOrDefault(no.getText().trim(),""));}});
        addRow(f,"Passenger name",name);addRow(f,"Train number",no);addRow(f,"Train name",train);addRow(f,"Class type",cls);addRow(f,"Journey date (yyyy-MM-dd)",date);addRow(f,"Source station",source);addRow(f,"Destination station",destination);JButton book=button("Insert / Book Ticket"); f.add(new JLabel());f.add(book);book.addActionListener(e->{ if(empty(name,no,train,date,source,destination)||!no.getText().trim().matches("\\d+")||!validDate(date.getText().trim())){JOptionPane.showMessageDialog(this,"Complete all fields. Use a numeric train number and date yyyy-MM-dd.","Check details",JOptionPane.WARNING_MESSAGE);return;} Reservation r=new Reservation();r.pnr="PNR-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();r.passengerName=name.getText().trim();r.trainNumber=no.getText().trim();r.trainName=train.getText();r.travelClass=(String)cls.getSelectedItem();r.journeyDate=date.getText().trim();r.source=source.getText().trim();r.destination=destination.getText().trim();try{Database.save(r);JOptionPane.showMessageDialog(this,details(r),"Booking confirmed",JOptionPane.INFORMATION_MESSAGE);name.setText("");no.setText("");date.setText("");source.setText("");destination.setText("");}catch(SQLException x){problem(x);}});p.add(f,BorderLayout.CENTER);JButton cancel=new JButton("Cancel a booking");cancel.addActionListener(e->cards.show(pages,"cancel"));p.add(cancel,BorderLayout.SOUTH);return p; }
    private JPanel cancelPage() { JPanel p=base("Cancel a Booking"); JPanel f=new JPanel(new GridLayout(0,2,10,10));JTextField pnr=new JTextField();JTextArea info=new JTextArea();info.setEditable(false);info.setLineWrap(true);info.setWrapStyleWord(true);final Reservation[] current=new Reservation[1];JButton fetch=button("Fetch");JButton confirm=new JButton("Confirm cancellation");confirm.setEnabled(false);addRow(f,"PNR number",pnr);f.add(new JLabel());f.add(fetch);f.add(new JLabel("Booking details"));f.add(new JScrollPane(info));f.add(new JLabel());f.add(confirm);fetch.addActionListener(e->{try{current[0]=Database.find(pnr.getText().trim());if(current[0]==null){info.setText("No booking found for that PNR.");confirm.setEnabled(false);}else{info.setText(details(current[0]));confirm.setEnabled(true);}}catch(SQLException x){problem(x);}});confirm.addActionListener(e->{if(JOptionPane.showConfirmDialog(this,"Are you sure you want to cancel this booking?","Confirm cancellation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)try{Database.cancel(current[0].pnr);JOptionPane.showMessageDialog(this,"Booking cancelled successfully.");info.setText("");pnr.setText("");confirm.setEnabled(false);}catch(SQLException x){problem(x);}});p.add(f,BorderLayout.CENTER);JButton back=new JButton("Back to booking");back.addActionListener(e->cards.show(pages,"book"));p.add(back,BorderLayout.SOUTH);return p; }
    private void addRow(JPanel p,String label,JComponent field){p.add(new JLabel(label));p.add(field);} private boolean empty(JTextField... a){for(JTextField x:a)if(x.getText().trim().isEmpty())return true;return false;}private boolean validDate(String s){try{LocalDate.parse(s,DateTimeFormatter.ISO_LOCAL_DATE);return true;}catch(DateTimeParseException e){return false;}}private String details(Reservation r){return "PNR: "+r.pnr+"\nPassenger: "+r.passengerName+"\nTrain: "+r.trainNumber+" - "+r.trainName+"\nClass: "+r.travelClass+"\nJourney: "+r.journeyDate+"\nRoute: "+r.source+" to "+r.destination;}private void problem(Exception e){JOptionPane.showMessageDialog(this,"Database operation could not be completed: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);} public static void main(String[] args){SwingUtilities.invokeLater(()->{try{Database.initialise();new ReservationApp().setVisible(true);}catch(SQLException e){JOptionPane.showMessageDialog(null,"Unable to start database: "+e.getMessage());}});}
}
